POST http://localhost:5678/webhook-test/assistente-pessoal
Content-Type: application/json

{
    "chatId": "14785",
    "mensagem": "Como está o tempo hoje?"
}


###
GET http://localhost:3000/tecnologias

###
GET http://localhost:3000/projetos/1